#theme: jekyll-theme-minimal
remote_theme: riggraz/no-style-please
title: Charlotte Rodriguez's homepage
url: https://chrdz.github.io/
#description: [Add description of the website here.]
github:
  is_project_page: false
